export const ADD_BASKET_INGREDIENT = 'ADD_BASKET_ITEM';
export const DELETE_BASKET_ITEM_BY_INDEX = 'DELETE_BASKET_ITEM_BY_INDEX';
export const BASKET_UPDATE_BY_SORT = 'BASKET_UPDATE_BY_SORT';
export const RESET_BASKET = 'RESET_BASKET';