export const ACTIVATE_INGREDIENTS_DETAILS: 'ACTIVATE_INGREDIENTS_DETAILS' = 'ACTIVATE_INGREDIENTS_DETAILS';
export const RESET_INGREDIENTS_DETAILS: 'RESET_INGREDIENTS_DETAILS' = 'RESET_INGREDIENTS_DETAILS';
