export const ACTIVATE_ORDER_INGREDIENTS_DETAILS: 'ACTIVATE_ORDER_INGREDIENTS_DETAILS' = 'ACTIVATE_ORDER_INGREDIENTS_DETAILS';
export const RESET_ORDER_INGREDIENTS_DETAILS: 'RESET_ORDER_INGREDIENTS_DETAILS' = 'RESET_ORDER_INGREDIENTS_DETAILS';
