export const WS_CONNECTION_OPEN_ALL: 'WS_CONNECTION_START_ALL' = 'WS_CONNECTION_START_ALL';
export const WS_CONNECTION_OPEN_PROFILE: 'WS_CONNECTION_START_PROFILE' = 'WS_CONNECTION_START_PROFILE';

export const WS_CONNECTION_CLOSE_ALL: 'WS_CONNECTION_CLOSE_ALL' = 'WS_CONNECTION_CLOSE_ALL';
export const WS_CONNECTION_CLOSE_PROFILE: 'WS_CONNECTION_CLOSE_PROFILE' = 'WS_CONNECTION_CLOSE_PROFILE';

export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
